! This file was generated by: python weno.py
module weno
contains
subroutine weno5(q, ql, qr, num_eqn, maxnx, num_ghost)

  implicit none

  integer,          intent(in)  :: num_eqn, maxnx, num_ghost
  double precision, intent(in)  :: q(num_eqn,maxnx+2*num_ghost)
  double precision, intent(out) :: ql(num_eqn,maxnx+2*num_ghost), qr(num_eqn,maxnx+2*num_ghost)

  integer :: i, m
  double precision :: sigma0, &
sigma1, &
sigma2, &
omega1, &
omega5, &
omega0, &
omega4, &
omega3, &
omega2, &
fr1, &
fr5, &
fr0, &
fr4, &
fr3, &
fr2, &
fs0, &
fs1

  do i = num_ghost-1, maxnx+num_ghost+1
    do m = 1, num_eqn
      sigma0 = 3.3333333333333333333333333333333333d0*q(m,i+0)*q(m,i+0) - &
      10.333333333333333333333333333333333d0*q(m,i+0)*q(m,i+1) + &
      3.6666666666666666666666666666666667d0*q(m,i+0)*q(m,i+2) + &
      8.3333333333333333333333333333333333d0*q(m,i+1)*q(m,i+1) - &
      6.3333333333333333333333333333333333d0*q(m,i+1)*q(m,i+2) + &
      1.3333333333333333333333333333333333d0*q(m,i+2)*q(m,i+2)
sigma1 = 4.3333333333333333333333333333333333d0*q(m,i+0)*q(m,i+0) - &
      4.3333333333333333333333333333333333d0*q(m,i+0)*q(m,i+1) - &
      4.3333333333333333333333333333333333d0*q(m,i+0)*q(m,i-1) + &
      1.3333333333333333333333333333333333d0*q(m,i+1)*q(m,i+1) + &
      1.6666666666666666666666666666666667d0*q(m,i+1)*q(m,i-1) + &
      1.3333333333333333333333333333333333d0*q(m,i-1)*q(m,i-1)
sigma2 = 3.3333333333333333333333333333333333d0*q(m,i+0)*q(m,i+0) - &
      10.333333333333333333333333333333333d0*q(m,i+0)*q(m,i-1) + &
      3.6666666666666666666666666666666667d0*q(m,i+0)*q(m,i-2) + &
      8.3333333333333333333333333333333333d0*q(m,i-1)*q(m,i-1) - &
      6.3333333333333333333333333333333333d0*q(m,i-1)*q(m,i-2) + &
      1.3333333333333333333333333333333333d0*q(m,i-2)*q(m,i-2)
omega0 = 0.1d0/(sigma0 + 0.00000099999999999999995474811182588625869d0)*(sigma0 + &
      0.00000099999999999999995474811182588625869d0)
omega1 = 0.6d0/(sigma1 + 0.00000099999999999999995474811182588625869d0)*(sigma1 + &
      0.00000099999999999999995474811182588625869d0)
omega2 = 0.3d0/(sigma2 + 0.00000099999999999999995474811182588625869d0)*(sigma2 + &
      0.00000099999999999999995474811182588625869d0)
omega3 = 0.3d0/(sigma0 + 0.00000099999999999999995474811182588625869d0)*(sigma0 + &
      0.00000099999999999999995474811182588625869d0)
omega4 = 0.6d0/(sigma1 + 0.00000099999999999999995474811182588625869d0)*(sigma1 + &
      0.00000099999999999999995474811182588625869d0)
omega5 = 0.1d0/(sigma2 + 0.00000099999999999999995474811182588625869d0)*(sigma2 + &
      0.00000099999999999999995474811182588625869d0)
fr0 = 1.8333333333333333333333333333333333d0*q(m,i+0) - &
      1.1666666666666666666666666666666667d0*q(m,i+1) + &
      0.33333333333333333333333333333333333d0*q(m,i+2)
fr1 = 0.83333333333333333333333333333333333d0*q(m,i+0) - &
      0.16666666666666666666666666666666667d0*q(m,i+1) + &
      0.33333333333333333333333333333333333d0*q(m,i-1)
fr2 = 0.33333333333333333333333333333333333d0*q(m,i+0) + &
      0.83333333333333333333333333333333333d0*q(m,i-1) - &
      0.16666666666666666666666666666666667d0*q(m,i-2)
fr3 = 0.33333333333333333333333333333333333d0*q(m,i+0) + &
      0.83333333333333333333333333333333333d0*q(m,i+1) - &
      0.16666666666666666666666666666666667d0*q(m,i+2)
fr4 = 0.83333333333333333333333333333333333d0*q(m,i+0) + &
      0.33333333333333333333333333333333333d0*q(m,i+1) - &
      0.16666666666666666666666666666666667d0*q(m,i-1)
fr5 = 1.8333333333333333333333333333333333d0*q(m,i+0) - &
      1.1666666666666666666666666666666667d0*q(m,i-1) + &
      0.33333333333333333333333333333333333d0*q(m,i-2)
fs0 = (fr0*omega0 + fr1*omega1 + fr2*omega2)/(omega0 + omega1 + omega2)
fs1 = (fr3*omega3 + fr4*omega4 + fr5*omega5)/(omega3 + omega4 + omega5)
ql(m,i) = fs0
qr(m,i) = fs1
    end do
  end do

end subroutine

subroutine weno5_mapped(q, ql, qr, num_eqn, maxnx, num_ghost, beta, varpi, coeffs)

  implicit none

  integer,          intent(in)  :: num_eqn, maxnx, num_ghost
  double precision, intent(in)  :: q(num_eqn,maxnx+2*num_ghost)
  double precision, intent(out) :: ql(num_eqn,maxnx+2*num_ghost), qr(num_eqn,maxnx+2*num_ghost)
  double precision, intent(in)  :: &
                beta(maxnx+2*num_ghost,0:3-1,0:3-1,0:3-1), &
                varpi(maxnx+2*num_ghost,0:1,0:3-1), &
                coeffs(maxnx+2*num_ghost,0:1,0:3-1,0:3-1)

  integer :: i, m
  double precision :: sigma0, &
sigma1, &
sigma2, &
omega1, &
omega5, &
omega0, &
omega4, &
omega3, &
omega2, &
fr1, &
fr5, &
fr0, &
fr4, &
fr3, &
fr2, &
fs0, &
fs1

  do i = num_ghost-1, maxnx+num_ghost+1
    do m = 1, num_eqn
      sigma0 = beta(i,0,0,0)*q(m,i+0)*q(m,i+0) + beta(i,0,0,1)*q(m,i+0)*q(m,i+1) + beta &
      (i,0,0,2)*q(m,i+0)*q(m,i+2) + beta(i,0,1,1)*q(m,i+1)*q(m,i+1) + &
      beta(i,0,1,2)*q(m,i+1)*q(m,i+2) + beta(i,0,2,2)*q(m,i+2)*q(m,i+2)
sigma1 = beta(i,1,0,0)*q(m,i-1)*q(m,i-1) + beta(i,1,0,1)*q(m,i+0)*q(m,i-1) + beta &
      (i,1,0,2)*q(m,i+1)*q(m,i-1) + beta(i,1,1,1)*q(m,i+0)*q(m,i+0) + &
      beta(i,1,1,2)*q(m,i+0)*q(m,i+1) + beta(i,1,2,2)*q(m,i+1)*q(m,i+1)
sigma2 = beta(i,2,0,0)*q(m,i-2)*q(m,i-2) + beta(i,2,0,1)*q(m,i-1)*q(m,i-2) + beta &
      (i,2,0,2)*q(m,i+0)*q(m,i-2) + beta(i,2,1,1)*q(m,i-1)*q(m,i-1) + &
      beta(i,2,1,2)*q(m,i+0)*q(m,i-1) + beta(i,2,2,2)*q(m,i+0)*q(m,i+0)
omega0 = varpi(i,0,0)/(sigma0 + 0.00000099999999999999995474811182588625869d0)*( &
      sigma0 + 0.00000099999999999999995474811182588625869d0)
omega1 = varpi(i,0,1)/(sigma1 + 0.00000099999999999999995474811182588625869d0)*( &
      sigma1 + 0.00000099999999999999995474811182588625869d0)
omega2 = varpi(i,0,2)/(sigma2 + 0.00000099999999999999995474811182588625869d0)*( &
      sigma2 + 0.00000099999999999999995474811182588625869d0)
omega3 = varpi(i,1,0)/(sigma0 + 0.00000099999999999999995474811182588625869d0)*( &
      sigma0 + 0.00000099999999999999995474811182588625869d0)
omega4 = varpi(i,1,1)/(sigma1 + 0.00000099999999999999995474811182588625869d0)*( &
      sigma1 + 0.00000099999999999999995474811182588625869d0)
omega5 = varpi(i,1,2)/(sigma2 + 0.00000099999999999999995474811182588625869d0)*( &
      sigma2 + 0.00000099999999999999995474811182588625869d0)
fr0 = coeffs(i,0,0,0)*q(m,i+0) + coeffs(i,0,0,1)*q(m,i+1) + coeffs(i,0,0,2)*q( &
      m,i+2)
fr1 = coeffs(i,0,1,0)*q(m,i-1) + coeffs(i,0,1,1)*q(m,i+0) + coeffs(i,0,1,2)*q( &
      m,i+1)
fr2 = coeffs(i,0,2,0)*q(m,i-2) + coeffs(i,0,2,1)*q(m,i-1) + coeffs(i,0,2,2)*q( &
      m,i+0)
fr3 = coeffs(i,1,0,0)*q(m,i+0) + coeffs(i,1,0,1)*q(m,i+1) + coeffs(i,1,0,2)*q( &
      m,i+2)
fr4 = coeffs(i,1,1,0)*q(m,i-1) + coeffs(i,1,1,1)*q(m,i+0) + coeffs(i,1,1,2)*q( &
      m,i+1)
fr5 = coeffs(i,1,2,0)*q(m,i-2) + coeffs(i,1,2,1)*q(m,i-1) + coeffs(i,1,2,2)*q( &
      m,i+0)
fs0 = (fr0*omega0 + fr1*omega1 + fr2*omega2)/(omega0 + omega1 + omega2)
fs1 = (fr3*omega3 + fr4*omega4 + fr5*omega5)/(omega3 + omega4 + omega5)
ql(m,i) = fs0
qr(m,i) = fs1
    end do
  end do

end subroutine
end module weno